max-line-length: 110

pycodestyle:
  options:
    max-line-length: 110
  disable:
    - E203

pylint:
  options:
    max-line-length: 110
  disable:
    - too-many-locals
    - too-many-statements
    - too-many-branches
    - c-extension-no-member

pyflakes:
  disable:
    - F401

mccabe:
  run: false

bandit:
  run: true
