version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
  allow:
  - dependency-type: all
  ignore:
  - dependency-name: none
    versions:
    - ">= 0"
- package-ecosystem: npm
  directory: "/geoportal"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/admin"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/doc"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/docker/test-app-db"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: none
    versions:
    - ">= 0"
- package-ecosystem: docker
  directory: "/docker/test-db"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: none
    versions:
    - ">= 0"
- package-ecosystem: docker
  directory: "/docker/test-external-db"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: none
    versions:
    - ">= 0"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/docker/config"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/docker/qgisserver"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/geoportal/c2cgeoportal_geoportal/scaffolds/create/ci"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/docker/qgisserver"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/docker/qgisserver/python/3.6"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/docker/qgisserver/python/3.8"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
