# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: /geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}/ci
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: /docker/qgisserver/python/3.8
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: /ci
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: /doc
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: pip
    directory: /docker/qgisserver/tests
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /doc
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /admin
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /docker/config
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /docker/qgisserver
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /docker/test-db
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /docker/test-mapserver
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /geoportal/c2cgeoportal_geoportal/scaffolds/advance_create/{{cookiecutter.project}}/geoportal
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: docker
    directory: /geoportal/c2cgeoportal_geoportal/scaffolds/create/{{cookiecutter.project}}
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none

  - package-ecosystem: npm
    directory: /geoportal
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: npm
    directory: /admin
    schedule:
      interval: monthly
    ignore:
      - dependency-name: bootstrap
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
  - package-ecosystem: npm
    directory: /doc
    schedule:
      interval: monthly
    ignore:
      - dependency-name: none
