# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/1.2.6/tag_publish/schema.json

docker:
  images:
    - name: camptocamp/geomapfish
    - name: camptocamp/geomapfish-config
    - name: camptocamp/geomapfish-tools
    - name: camptocamp/geomapfishapp-geoportal
    - name: camptocamp/geomapfish-qgisserver
      group: qgis-3.34-gdal3.8
      tags:
        - gmf{version}-qgis3.34-gdal3.8
    - name: camptocamp/geomapfish-qgisserver
      group: qgis-3.34
      tags:
        - gmf{version}-qgis3.34
    - name: camptocamp/geomapfish-qgisserver
      group: qgis-3.40-gdal3.10
      tags:
        - gmf{version}-qgis3.40-gdal3.10
    - name: camptocamp/geomapfish-qgisserver
      group: qgis-3.40
      tags:
        - gmf{version}-qgis3.40
    - name: camptocamp/geomapfish-qgisserver
      group: qgis-ltr
      tags:
        - gmf{version}-qgisltr
pypi:
  versions_type:
    - version_tag
  packages:
    - folder: commons
      group: pypi
    - folder: geoportal
      group: pypi
    - folder: admin
      group: pypi
