package geomapfish

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

import java.lang.Math


class Basic extends Simulation {
    val random = new util.Random

    /*
     * CONFIG
     */

    val host = "geomapfish-demo.camptocamp.net"
    val theme = "Transport"
    val group = theme
    val lang = "fr"
    val raster_layers = "srtm,aster"

    val fts_choises = ('a' to 'z') ++ ('0' to '9')

    case class Extent(xMin: Int, yMin: Int, xMax: Int, yMax: Int)
    val extent = Extent(512691, 149736, 551491, 171836)

    val instance_ids = Array("1.6")
    val resolutions = Array(0.05, 0.1, 0.25, 0.5, 1, 2, 5, 10, 20, 50, 100, 200)
    val layers = Map(
        "1.6" -> Array("fuel", "bus_stop", "parking")
    )
    val layers_rules = Map(
        "1.6" -> Array(
            ("fuel", "fuel"),
            ("bus_stop", "Arr%C3%AAts%20de%20bus"),
            ("parking", "Stations%20service")
         )
    )

    val img_width = 2060
    val img_height = 1215

    val nbUser = 1
    val spaceTime = 20


    /*
     * /CONFIG
     */

    val basicTime = 100.0
    val nbTimes = Math.ceil(nbUser * spaceTime / basicTime).toInt
    val rampTime = nbUser * spaceTime

    val cache_version = random.nextInt()
    val defaults_feeder = Array(Map(
        "theme" -> theme,
        "group" -> group,
        "lang" ->lang,
        "cache_version" -> cache_version,
        "role" -> "6",
        "limit" -> 10
    )).random

    def randX: Int = extent.xMin + random.nextInt(extent.xMax - extent.xMin)
    def randY: Int = extent.yMin + random.nextInt(extent.yMax - extent.yMin)
    def getBbox(width: Int, height: Int)(x: Int, y: Int, resolution: Double): String = {
        val x2 = x + width * resolution
        val y2 = y + height * resolution
        s"${x},${y},${x2},${y2}"
    }
    val common_bbox = getBbox(img_width, img_height)_


    val map_feeder = new Feeder[String] {
        // always return true as this feeder can be polled infinitively
        override def hasNext = true
        override def next: Map[String, String] = {
            val instance_id = instance_ids.get(random.nextInt(instance_ids.length))
            val (layer, rule) = layers_rules.get(instance_id).get(random.nextInt(layers_rules.get(instance_id).size))
            val map = Map(
                "instance_id" -> instance_id.toString,
                // to debug
                // "suffix" -> "_" + instance_id,
                "suffix" -> "",
                "x" -> randX.toString,
                "y" -> randY.toString,
                "layer" -> layers.get(instance_id).get(random.nextInt(layers.get(instance_id).get.length)),
                "scale" -> (72.0 / resolutions.get(random.nextInt(resolutions.length)) * 39.37).toString,
                "layer_rule" -> layer,
                "rule" -> rule,
                "lon" -> randX.toString,
                "lat" -> randY.toString,
                "query" -> random.nextString(random.nextInt(5) + 1).foldLeft("") { (s, i) => s + fts_choises.charAt(random.nextInt(fts_choises.length))},
                "coordinates" -> s"[[${randX},${randY}],[${randX},${randY}]]"
            )

            map ++ resolutions.map(resolution =>
               (f"BBOX_$resolution%.3f", common_bbox(randX, randY, resolution))
            ).toMap
        }
    }

    val httpProtocol = http
        .baseURL(s"http://${host}")
        .inferHtmlResources(WhiteList(s"http://${host}/*"), BlackList())
        .acceptHeader("image/png,image/*;q=0.8,*/*;q=0.5")
        .acceptEncodingHeader("gzip, deflate")
        .acceptLanguageHeader(s"${lang};q=0.5")
        .connection("keep-alive")
        .contentTypeHeader("application/x-www-form-urlencoded; charset=UTF-8")
        .userAgentHeader("Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0")

    val headers_0 = Map(
        "Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    )

    val headers_3 = Map(
        "Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "X-Requested-With" -> "XMLHttpRequest"
    )

    val headers_8 = Map(
        "Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Pragma" -> "no-cache",
        "X-Requested-With" -> "XMLHttpRequest"
    )

    val headers_18 = Map("Accept" -> "*/*")

    val uri = s"http://${host}/"

    val scn1 = scenario("BasicSimulation")
        .feed(defaults_feeder)
        .feed(map_feeder)
        .exec(http("index${suffix}").get("/${instance_id}/").headers(headers_0))
        .exec(http("mapserv_GetMap${suffix}")
            .get("/${instance_id}/wsgi/mapserv_proxy")
            .queryParam("cache_version", "${cache_version}")
            .queryParam("SERVICE", "WMS")
            .queryParam("VERSION", "1.1.1")
            .queryParam("REQUEST", "GetMap")
            .queryParam("FORMAT", "image/png")
            .queryParam("TRANSPARENT", "TRUE")
            .queryParam("LAYERS", "${layer}")
            .queryParam("STYLES", "")
            .queryParam("SRS", "EPSG:21781")
            .queryParam("BBOX", "BBOX_20_000")
            .queryParam("WIDTH", img_width)
            .queryParam("HEIGHT", img_height))
        .exec(http("mapserv_GetMap${suffix}")
            .get("/${instance_id}/wsgi/mapserv_proxy")
            .queryParam("cache_version", "${cache_version}")
            .queryParam("SERVICE", "WMS")
            .queryParam("VERSION", "1.1.1")
            .queryParam("REQUEST", "GetMap")
            .queryParam("FORMAT", "image/png")
            .queryParam("TRANSPARENT", "TRUE")
            .queryParam("LAYERS", "${layer}")
            .queryParam("STYLES", "")
            .queryParam("SRS", "EPSG:21781")
            .queryParam("BBOX", "BBOX_20_000")
            .queryParam("WIDTH", img_width)
            .queryParam("HEIGHT", img_height))
        .pause(8)
        .feed(map_feeder)
    val scn2 = (0 until nbTimes).foldLeft(scn1) { (s, i) =>
        s.feed(map_feeder)
            .exec(http("raster${suffix}")
                .get("/${instance_id}/wsgi/raster")
                .queryParam("_ds", "${cache_version}")
                .queryParam("lon", "${lon}")
                .queryParam("lat", "${lat}")
                .headers(headers_3))
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/lib/cgxp/geoext/resources/images/gray/anchor.png"))
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/lib/cgxp/geoext/resources/images/gray/anchor-top.png"))
            .pause(1)
            .feed(map_feeder)
            .exec(http("raster${suffix}")
                .get("/${instance_id}/wsgi/raster")
                .queryParam("_ds", "${cache_version}")
                .queryParam("lon", "${lon}")
                .queryParam("lat", "${lat}")
                .headers(headers_3))
            .pause(1)
            .feed(map_feeder)
            .exec(http("raster${suffix}")
                .get("/${instance_id}/wsgi/raster")
                .queryParam("_ds", "${cache_version}")
                .queryParam("lon", "${lon}")
                .queryParam("lat", "${lat}")
                .headers(headers_3))
            .pause(3)
            .feed(map_feeder)
            .exec(http("profile${suffix}").post(uri + "${instance_id}/wsgi/profile.json").headers(headers_8)
                .formParam("layers", raster_layers)
                .formParam("geom", """{"type":"LineString","coordinates":${coordinates}}""")
                .formParam("nbPoints", "100"))
            .pause(1)
            .feed(map_feeder)
            .exec(http("profile${suffix}").post(uri + "${instance_id}/wsgi/profile.json").headers(headers_8)
                .formParam("layers", raster_layers)
                .formParam("geom", """{"type":"LineString","coordinates":${coordinates}}""")
                .formParam("nbPoints", "100"))
            .pause(2)
            .feed(map_feeder)
            .exec(http("profile${suffix}").post(uri + "${instance_id}/wsgi/profile.json").headers(headers_8)
                .formParam("layers", raster_layers)
                .formParam("geom", """{"type":"LineString","coordinates":${coordinates}}""")
                .formParam("nbPoints", "100"))
            .pause(7)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_20_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_10_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_5_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_2_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_1_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_0_500")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(2)
            .feed(map_feeder)
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/lib/cgxp/ext/Ext/resources/images/default/grid/loading.gif"))
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(1)
            .feed(map_feeder)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(1)
            .feed(map_feeder)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(1)
            .feed(map_feeder)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(1)
            .feed(map_feeder)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(2)
            .feed(map_feeder)
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/lib/cgxp/ext/Ext/resources/images/gray/form/clear-trigger.gif"))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_200_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(9)
            .feed(map_feeder)
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/lib/cgxp/core/src/theme/img/legend.png"))
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/lib/cgxp/core/src/theme/img/legend-up.png"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .pause(2)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_100_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_50_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_20_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_10_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_5_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_2_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_1_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_0_500")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(2)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_0_250")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_0_100")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .pause(2)
            .exec(http("short${suffix}")
                .post(uri + "${instance_id}/wsgi/short/create").headers(headers_8)
                .formParam("url", uri + "${instance_id}/theme/${theme}?map_x=${x}&map_y=${y}&map_zoom=10"))
            .pause(9)
    }
    val scn3 = scn2.exec(http("login${suffix}")
            .post(uri + "${instance_id}/wsgi/login")
            .headers(headers_8)
            .formParam("login", "demo")
            .formParam("password", "demo")
            .formParam("newPassword", "")
            .formParam("confirmNewPassword", ""))
        .exec(http("index${suffix}")
            .post(uri + "${instance_id}/theme/${theme}?map_x=${x}&map_y=${y}&map_zoom=10")
            .headers(headers_0)
            .formParam("login", "demo")
            .formParam("password", "demo")
            .formParam("newPassword", "")
            .formParam("confirmNewPassword", ""))
        .exec(http("viewer${suffix}")
            .get("/${instance_id}/wsgi/viewer.js")
            .queryParam("lang", "${lang}")
            .queryParam("permalink_themes", "${theme}")
            .queryParam("role", "${role}")
            .queryParam("cache_version", "${cache_version}")
            .headers(headers_18))
        .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/lib/cgxp/core/src/theme/img/location_chooser.png"))
        .pause(1)
    val scn4 = (0 until nbTimes).foldLeft(scn3) { (s, i) =>
        s.feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_0_100")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_0_100")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer_rule}")
                .queryParam("RULE", "${rule}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer_rule}")
                .queryParam("RULE", "${rule}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer_rule}")
                .queryParam("RULE", "${rule}"))
            .pause(3)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_2_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(5)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(1)
            .feed(map_feeder)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .feed(map_feeder)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(1)
            .feed(map_feeder)
            .exec(http("fulltextsearch${suffix}")
                .get("/${instance_id}/wsgi/fulltextsearch")
                .queryParam("_dc", "${cache_version}")
                .queryParam("limit", "${limit}")
                .queryParam("query", "${query}")
                .headers(headers_18))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_10_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(4)
            .exec(http("raster${suffix}")
                .get("/${instance_id}/wsgi/raster")
                .queryParam("_ds", "${cache_version}")
                .queryParam("lon", "${lon}")
                .queryParam("lat", "${lat}")
                .headers(headers_3))
            .pause(2)
            .feed(map_feeder)
            .exec(http("raster${suffix}")
                .get("/${instance_id}/wsgi/raster")
                .queryParam("_ds", "${cache_version}")
                .queryParam("lon", "${lon}")
                .queryParam("lat", "${lat}")
                .headers(headers_3))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_5_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_2_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(4)
            .exec(http("profile${suffix}").post(uri + "${instance_id}/wsgi/profile.json").headers(headers_8)
                .formParam("layers", raster_layers)
                .formParam("geom", """{"type":"LineString","coordinates":${coordinates}}""")
                .formParam("nbPoints", "100"))
            .pause(5)
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .pause(3)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_2_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(1)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .pause(6)
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_5_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .feed(map_feeder)
            .exec(http("mapserv_GetMap${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetMap")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYERS", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("BBOX", "BBOX_5_000")
                .queryParam("WIDTH", img_width)
                .queryParam("HEIGHT", img_height))
            .pause(1)
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .feed(map_feeder)
            .exec(http("mapserv_GetLegendGraphic${suffix}")
                .get("/${instance_id}/wsgi/mapserv_proxy")
                .queryParam("cache_version", "${cache_version}")
                .queryParam("role", "${role}")
                .queryParam("SERVICE", "WMS")
                .queryParam("VERSION", "1.1.1")
                .queryParam("REQUEST", "GetLegendGraphic")
                .queryParam("FORMAT", "image/png")
                .queryParam("TRANSPARENT", "TRUE")
                .queryParam("LAYER", "${layer}")
                .queryParam("STYLES", "")
                .queryParam("SRS", "EPSG:21781")
                .queryParam("SCALE", "${scale}"))
            .pause(10)
            .exec(http("short${suffix}").post(uri + "${instance_id}/wsgi/short/create").headers(headers_8)
                .formParam("url", uri + "${instance_id}/theme/${theme}?map_x=${x}&map_y=${y}&map_zoom=5&tree_group_layers_${group}=${layer}"))
            .pause(11)
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/img/icons/tw_hover.png"))
            .exec(http("static${suffix}").get("/${instance_id}/wsgi/proj/${cache_version}/img/icons/ss_hover.png"))
            .pause(1)
    }

    setUp(scn4.inject(rampUsers(nbUser) over (rampTime seconds))).protocols(httpProtocol)
}
