---
strictness: veryhigh
max-line-length: 110
doc-warnings: True

ignore-paths:
  - node_modules
  - setup.py
  - CONST_create_template
  - scaffolds
  - docker/qgisserver

pycodestyle:
  disable:
    - E203 # Whitespace before ':'
    - E722 # Do not use bare 'except'

pydocstyle:
  disable:
    - D100 # Missing docstring in public module
    - D102 # Missing docstring in public method
    - D104 # Missing docstring in public package
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__
    - D200 # One-line docstring should fit on one line with quotes
    - D202 # No blank lines allowed after function docstring (found 1)
    - D203 # 1 blank line required before class docstring (found 0)
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section ('Arguments')
    - D412 # No blank lines allowed between a section header and its content ('Arguments')
    - D413 # Missing blank line after last section ('Arguments')

pylint:
  options:
    extension-pkg-allow-list:
      - 'lxml'
  disable:
    - missing-module-docstring
    - missing-function-docstring
    - missing-timeout # Default timeout set by c2cwsgiutils

pyflakes:
  disable:
    - F401 # imported but unused

mypy:
  run: true

bandit:
  run: true
  options:
    config: .bandit.yaml

mccabe:
  run: false
