inherits:
  - utils:tests
  - utils:pre-commit
ruff:
  disable:
    - PT009 # Use a regular `assert` instead of unittest-style `assertAlmostEqual`
    - PT027 # Use `pytest.raises` instead of unittest-style `assertRaises`
    - E741 # Ambiguous variable name: `l`
    - B904 # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
