inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks
  - utils:unsafe
  - utils:c2cwsgiutils

ignore-paths:
  - commons/setup.py
  - geoportal/setup.py
  - admin/setup.py
  - geoportal/c2cgeoportal_geoportal/scaffolds
  - docker/qgisserver
  - commons/c2cgeoportal_commons/alembic/main
  - commons/c2cgeoportal_commons/alembic/static

mypy:
  options:
    python_version: '3.10'

ruff:
  disable:
    - D102 # Missing docstring in public method
    - D107 # Missing docstring in `__init__`
