---
strictness: veryhigh

ignore-paths:
  - node_modules
  - setup.py
  - CONST_create_template

pep8:
  disable:
    - E203
  options:
    max-line-length: 110

mypy:
  run: true

mccabe:
  run: false
