inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

ignore-paths:
  - commons/setup.py
  - geoportal/setup.py
  - admin/setup.py
  - geoportal/c2cgeoportal_geoportal/scaffolds
  - docker/qgisserver

pydocstyle:
  disable:
    - D102 # Missing docstring in public method
    - D104 # Missing docstring in public package
    - D105 # Missing docstring in magic method
    - D107 # Missing docstring in __init__
    - D200 # One-line docstring should fit on one line with quotes
    - D202 # No blank lines allowed after function docstring (found 1)
    - D203 # 1 blank line required before class docstring (found 0)
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section ('Arguments')
    - D412 # No blank lines allowed between a section header and its content ('Arguments')

bandit:
  options:
    config: .bandit.yaml
