---
version: '2.3'

services:
  db:
    image: camptocamp/geomapfish-test-db
    environment:
      - POSTGRES_USER=www-data
      - POSTGRES_PASSWORD=www-data
      - POSTGRES_DB=geomapfish_tests

  qgisserver-tests:
    image: camptocamp/geomapfish-qgisserver-tests
    volumes:
      - ./docker/qgisserver/geomapfish_qgisserver/:/var/www/plugins/geomapfish_qgisserver/
      - ./docker/qgisserver/tests:/src/tests/
      - ./commons/c2cgeoportal_commons/:/opt/c2cgeoportal/commons/c2cgeoportal_commons/
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=www-data
      - PGPASSWORD=www-data
      - PGDATABASE=geomapfish_tests
      - PGSCHEMA=main
      - PGSCHEMA_STATIC=main_static

  mapserver:
    image: camptocamp/geomapfish-test-mapserver
    user: www-data
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=www-data
      - PGPASSWORD=www-data
      - PGDATABASE=geomapfish_tests
      - 'MAPSERVER_DATA_SUBSELECT=SELECT ST_Collect(ra.area)
        FROM main.restrictionarea AS ra, main.role_restrictionarea AS rra,
        main.layer_restrictionarea AS lra, main.treeitem AS la
        WHERE rra.role_id in (%role_ids%) AND rra.restrictionarea_id = ra.id
        AND lra.restrictionarea_id = ra.id AND lra.layer_id = la.id AND la.name = '
      - 'MAPSERVER_DATA_NOAREA_SUBSELECT=SELECT rra.role_id
        FROM main.restrictionarea AS ra, main.role_restrictionarea AS rra,
        main.layer_restrictionarea AS lra, main.treeitem AS la
        WHERE rra.restrictionarea_id = ra.id AND lra.restrictionarea_id = ra.id
        AND lra.layer_id = la.id AND la.name = '
      - 'MAPSERVER_JOIN_TABLES=main.restrictionarea AS ra, main.role_restrictionarea AS rra,
        main.layer_restrictionarea AS lra, main.treeitem AS la'
      - 'MAPSERVER_JOIN_WHERE=rra.role_id in (%role_ids%) AND rra.restrictionarea_id = ra.id AND
        lra.restrictionarea_id = ra.id AND lra.layer_id = la.id AND la.name = '

  tilecloudchain:
    image: camptocamp/tilecloud-chain:1.13
    user: www-data
    restart: unless-stopped
    environment:
      - TILEGENERATION_CONFIGFILE=/etc/tilegeneration/config.yaml
    volumes:
      - ./docker/test-tilecloudchain:/etc/tilegeneration

  tests:
    image: camptocamp/geomapfish-tools
    volumes:
      - ./commons/c2cgeoportal_commons:/opt/c2cgeoportal/commons/c2cgeoportal_commons
      - ./geoportal/c2cgeoportal_geoportal:/opt/c2cgeoportal/geoportal/c2cgeoportal_geoportal
      - ./admin/c2cgeoportal_admin:/opt/c2cgeoportal/admin/c2cgeoportal_admin
      - ./admin/tests:/opt/c2cgeoportal/admin/tests
      - ./commons/tests:/opt/c2cgeoportal/commons/tests
      - ./geoportal/tests:/opt/c2cgeoportal/geoportal/tests
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=www-data
      - PGPASSWORD=www-data
      - PGDATABASE=geomapfish_tests
      - PGSSLMODE=disable
      - CI=true
      - TEST=true
    entrypoint:
      - /usr/bin/eval-templates
    command:
      - tail
      - -f
      - /dev/null
