#!/usr/bin/env python3

import getpass
import os
import sys
import subprocess

os.environ["HOME_DIR"] = os.environ["HOME"]
os.environ["USER_NAME"] = getpass.getuser()
os.environ["USER_ID"] = str(os.getuid())
os.environ["GROUP_ID"] = str(os.getgid())

try:
    subprocess.check_call(["docker-compose", "run", "build"] + sys.argv[1:])
except subprocess.CalledProcessError as e:
    exit(e.returncode)
