---
name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  rebuild:
    runs-on: ubuntu-24.04
    name: Rebuild
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - int-{{cookiecutter.geomapfish_main_version_dash}}
          - prod-{{cookiecutter.geomapfish_main_version_dash}}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{'{{'}} matrix.branch }}

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'
      - run: python3 -m pip install --requirement=ci/requirements.txt
      - name: Environment information
        run: c2cciutils-env

      - name: Build
        run: ./build

      - name: Publish
        run: tag-publish --branch=${{'{{'}} matrix.branch }} --type=rebuild
