---
# The list (by include, exclude) of default files that will not be overwritten by the upgrade.
# That that can be extended with managed_files or reduced with unmanaged_files from the
# project.yaml file in the project root directory.
default_project_file:
  include:
    - geoportal/setup\.py
    - geoportal/vars\.yaml
    - geoportal/Makefile
    - geoportal/{{cookiecutter.package}}_geoportal/__init__\.py
    - geoportal/{{cookiecutter.package}}_geoportal/templates/.*
    - geoportal/{{cookiecutter.package}}_geoportal/locale/.*
    - geoportal/{{cookiecutter.package}}_geoportal/static/.*
    - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/.*
    - print/print-apps/.*
    - mapserver/.*
    - tilegeneration/config\.yaml\.tmpl
    - project\.yaml
    - docker-compose\.yaml
    - env\.project
    - README\.rst
    - \.github/workflows/main\.yaml
    - \.github/workflows/rebuild\.yaml
  exclude:
    - mapserver/demo\.map\.tmpl
    - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/image/favicon\.ico

# Files ignored when creating the diff files => will just be left untouched.
no_diff:
  - .*\.po
  - CONST_.+
  - .*/CONST_.+

# Files that will be present in the CONST_create_template but will not be considered in the upgrade.
# Used to provide the alt applications => does not disturb the user during upgrade.
extra:
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/mobile_alt\.html\.ejs
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/oeedit\.html\.ejs
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/Controllermobile_alt\.js
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/Controlleroeedit\.js
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/sass/mobile_alt\.scss
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/sass/vars_mobile_alt\.scss
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/sass/oeedit\.scss
  - geoportal/{{cookiecutter.package}}_geoportal/static-ngeo/js/apps/sass/vars_oeedit\.scss
  - geoportal/interfaces/desktop_alt\.html\.mako
  - geoportal/{{cookiecutter.package}}_geoportal/static/images/background-layer-button\.png
  - tests/test_testapp.py

# Automated file system operations:
# Remove some files or directories:
#  - action: remove
#    paths:
#      - <one file or directory>
# Move a file:
#  - action: move
#    from: <src file>
#    to: <dst file>
upgrade_files:
  - action: remove
    paths:
      - geoportal/tools/extract-messages.js
