#!/usr/bin/env python3

import argparse
import os.path
import subprocess
import sys


def main():
    parser = argparse.ArgumentParser(description="Publish Docker images")
    parser.add_argument(
        "--image", dest="images", action="append", help="The image to be exported"
    )
    parser.add_argument(
        "--service", default="dockerhub", help="Used repository",
    )
    parser.add_argument(
        "--no-trigger",
        dest="trigger",
        action="store_false",
        help="Disable triggerring OpenShift for an image update",
    )
    args = parser.parse_args()

    if "GITHUB_REF" in os.environ:
        ref = os.environ["GITHUB_REF"].split("/")

        if ref[1] != "heads":
            print("Not a branch")
            sys.exit(0)

        version = "/".join(ref[2:])
    else:
        if os.environ["TRAVIS_PULL_REQUEST"] == "true":
            print("Not deploying images for pull requests")
            sys.exit(0)

        version = os.environ["TRAVIS_BRANCH"]

    if version not in os.environ.get("HELM_RELEASE_NAMES", "").split(","):
        print("Not a release branch")
        sys.exit(0)

    print("Deploying images for tag {}".format(version))
    sys.stdout.flush()

    cmd = ["docker", "login"]
    if args.service == "dockerhub":
        if "GITHUB_REF" in os.environ:
            login = subprocess.check_output(
                ["gopass", "gs/ci/dockerhub/username"]
            ).decode()
            password = subprocess.check_output(["gopass", "gs/ci/dockerhub/password"])
        else:
            login = os.environ["DOCKER_USERNAME"]
            password = os.environ["DOCKER_PASSWORD"]
        prefix = ""
    elif args.service == "github":
        cmd += ["ghcr.io"]
        login = subprocess.check_output(["gopass", "gs/ci/github/username"]).decode()
        password = subprocess.check_output(["gopass", "gs/ci/github/token/gopass"])
        prefix = "ghcr.io/"
    else:
        print("Unknown service '{}'".format(args.service))
        sys.exit(1)

    cmd += ["--username=" + login, "--password-stdin"]
    process = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    output, output_err = process.communicate(input=password)
    if process.returncode != 0:
        if output:
            print(output.decode())
        if output_err:
            print(output_err.decode())
        sys.exit(1)

    for image in args.images:
        full_image = "camptocamp/{}-{}".format(os.environ["PROJECT"], image)
        src_image = "{}:latest".format(full_image)
        dest_image = "{}{}:{}".format(prefix, full_image, version)
        subprocess.check_call(["docker", "tag", src_image, dest_image])
        subprocess.check_call(["docker", "push", dest_image])

    if args.trigger:
        openshift_version = "3.11.0"
        openshift_hash = "0cbc58b"
        openshift_version_name = "openshift-origin-client-tools-v{}-{}-linux-64bit".format(
            openshift_version, openshift_hash
        )
        openshift_file = openshift_version_name + ".tar.gz"
        openshift_url = "https://github.com/openshift/origin/releases/download/v{}/{}".format(
            openshift_version, openshift_file
        )
        subprocess.check_call(["wget", "--quiet", openshift_url], cwd="/tmp")
        subprocess.check_call(["tar", "xfz", openshift_file], cwd="/tmp")
        oc = "/tmp/{}/oc".format(openshift_version_name)  # pylint: disable=invalid-name

        if "GITHUB_REF" in os.environ:
            subprocess.check_call(
                [
                    oc,
                    "login",
                    os.environ["OPENSHIFT_URL"],
                    "--token="
                    + subprocess.check_output(
                        [
                            "gopass",
                            "gs/ci/openshift/{}/token".format(
                                os.environ["OPENSHIFT_PROJECT"]
                            ),
                        ]
                    ).decode(),
                ]
            )
        else:
            subprocess.check_call(
                [
                    oc,
                    "login",
                    os.environ["OPENSHIFT_URL"],
                    "--token=" + os.environ["OPENSHIFT_TOKEN"],
                ]
            )

        for image in args.images:
            openshift_image_ref = "{}-c2cgeoportal-{}:{}".format(
                os.environ.get("OPENSHIFT_RELEASE", version), image, version
            )
            subprocess.check_call(
                [
                    oc,
                    "import-image",
                    openshift_image_ref,
                    "--scheduled=true",
                    "--reference-policy=local",
                    "--namespace=" + os.environ["OPENSHIFT_PROJECT"],
                ]
            )


if __name__ == "__main__":
    main()
