---
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: echo Disabled
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - none
