# Copyright (c) 2024-2025, Camptocamp SA
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.

# pylint: disable=invalid-name

"""
Add OGC server information in the theme for next generation clients.

Revision ID: 33528a10237c
Revises: 834a3cfc02f2
Create Date: 2025-09-09 12:06:52.561895
"""

import sqlalchemy as sa
from alembic import op
from c2c.template.config import config

# revision identifiers, used by Alembic.
revision = "33528a10237c"
down_revision = "834a3cfc02f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade."""
    schema = config["schema"]

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ogc_server",
        sa.Column(
            "map_protocol",
            sa.Enum("WMS", "OGC API - Maps", native_enum=False),
            nullable=False,
            server_default="WMS",
        ),
        schema=schema,
    )
    op.add_column("ogc_server", sa.Column("query_url", sa.Unicode(), nullable=True), schema=schema)
    op.add_column(
        "ogc_server",
        sa.Column(
            "query_protocol",
            sa.Enum("WMS/GetFeatureInfo", "WFS/GetFeature", "OGC API - Features", native_enum=False),
            nullable=False,
            server_default="WFS/GetFeature",
        ),
        schema=schema,
    )
    op.add_column(
        "ogc_server",
        sa.Column(
            "query_auth",
            sa.Enum("No auth", "Standard auth", "Geoserver auth", "Proxy", native_enum=False),
            nullable=False,
            server_default="Standard auth",
        ),
        schema=schema,
    )
    op.add_column("ogc_server", sa.Column("edit_url", sa.Unicode(), nullable=True), schema=schema)
    op.add_column(
        "ogc_server",
        sa.Column(
            "edit_protocol",
            sa.Enum("OGC API - Features", native_enum=False),
            nullable=True,
            server_default="OGC API - Features",
        ),
        schema=schema,
    )
    op.add_column(
        "ogc_server",
        sa.Column(
            "edit_auth",
            sa.Enum("No auth", "Standard auth", "Geoserver auth", "Proxy", native_enum=False),
            nullable=False,
            server_default="Standard auth",
        ),
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    schema = config["schema"]

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ogc_server", "edit_auth", schema=schema)
    op.drop_column("ogc_server", "edit_protocol", schema=schema)
    op.drop_column("ogc_server", "edit_url", schema=schema)
    op.drop_column("ogc_server", "query_auth", schema=schema)
    op.drop_column("ogc_server", "query_protocol", schema=schema)
    op.drop_column("ogc_server", "query_url", schema=schema)
    op.drop_column("ogc_server", "map_protocol", schema=schema)
    # ### end Alembic commands ###
