# Copyright (c) 2024-2025, Camptocamp SA
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.

# pylint: disable=invalid-name

"""
Uses a multipolygon for the restriction area.

Revision ID: 834a3cfc02f2
Revises: 2e57710fecfe
Create Date: 2025-08-27 09:30:20.421770
"""

import geoalchemy2.types
from alembic import op
from c2c.template.config import config

# revision identifiers, used by Alembic.
revision = "834a3cfc02f2"
down_revision = "2e57710fecfe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade."""
    schema = config["schema"]
    srid = config.get("srid")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restrictionarea",
        "area",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            srid=srid,
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=srid,
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        existing_nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    schema = config["schema"]
    srid = config.get("srid")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restrictionarea",
        "area",
        existing_type=geoalchemy2.types.Geometry(
            geometry_type="MULTIPOLYGON",
            srid=srid,
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
        ),
        type_=geoalchemy2.types.Geometry(
            geometry_type="POLYGON",
            srid=srid,
            dimension=2,
            from_text="ST_GeomFromEWKT",
            name="geometry",
            _spatial_index_reflected=True,
        ),
        existing_nullable=True,
        schema=schema,
    )
    # ### end Alembic commands ###
