#!/usr/bin/env python3

import os
import subprocess
import sys

docker_run = ["python", "docker-run"] if os.name == "nt" else ["./docker-run"]
dependencies = subprocess.check_output(docker_run + ["pip", "freeze"]).decode("utf-8").split("\n")
dependencies = [e for e in dependencies if "@" not in e or "#" not in e]

for filter_ in sys.argv[1:]:
    dependencies = [e for e in dependencies if not e.startswith(filter_ + "==")]

print(" ".join(dependencies))
