# The project Docker compose file.

volumes:
  postgresql_data:

services:
  config:
    extends:
      file: docker-compose-lib.yaml
      service: config

  print:
    extends:
      file: docker-compose-lib.yaml
      service: print
    volumes_from:
      - config:ro

  mapserver:
    extends:
      file: docker-compose-lib.yaml
      service: mapserver

    volumes_from:
      - config:ro
    volumes:
      - /var/sig:/var/sig:ro

  ## qgisserver:
  ##   extends:
  ##     file: docker-compose-lib.yaml
  ##     service: qgisserver
  ##   volumes_from:
  ##     - config:ro
  ##   environment:
  ##     - QGIS_SERVER_LANDING_PAGE_PROJECTS_DIRECTORIES=/etc/qgisserver/
  ##     # Or
  ##     - QGIS_SERVER_LANDING_PAGE_PROJECTS_PG_CONNECTIONS=...

  tinyows:
    extends:
      file: docker-compose-lib.yaml
      service: tinyows
    volumes_from:
      - config:ro

  # Standalone version
  redis:
    extends:
      file: docker-compose-lib.yaml
      service: redis

  # To test Kubernetes version
  # redis_master:
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: redis_master
  #
  # redis_slave:
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: redis_slave
  #   depends_on:
  #     - redis_master
  #
  # redis_sentinel:
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: redis_sentinel
  #   depends_on:
  #     - redis_master

  tilecloudchain:
    extends:
      file: docker-compose-lib.yaml
      service: tilecloudchain
    volumes_from:
      - config:ro

  tilegeneration_slave:
    extends:
      file: docker-compose-lib.yaml
      service: tilegeneration_slave
    volumes_from:
      - config:ro

  geoportal:
    extends:
      file: docker-compose-lib.yaml
      service: geoportal
    volumes_from:
      - config:ro
    volumes:
      - /var/sig:/var/sig:ro

  alembic:
    extends:
      file: docker-compose-lib.yaml
      service: alembic

  front:
    extends:
      file: docker-compose-lib.yaml
      service: front
    volumes_from:
      - config:ro

  # Rich image for project development with e.-g. vim, psql, ...
  tools:
    extends:
      file: docker-compose-lib.yaml
      service: tools
    volumes_from:
      - config:ro

  # db:
  #   extends:
  #     file: docker-compose-lib.yaml
  #     service: db
  #   volumes:
  #     - postgresql_data:/var/lib/postgresql/data
