#!/usr/bin/env python3

import requests

responce = requests.get("http://qgisserver", params={"SERVICE": "WMS", "REQUEST": "GetCapabilities"})

print(responce.status_code)
assert responce.ok
print(responce.headers["Content-Type"])
assert responce.headers["Content-Type"].split(";")[0] == "text/xml"
assert "private_layer" not in responce.text


responce = requests.get(
    "http://qgisserver", params={"SERVICE": "WMS", "REQUEST": "GetCapabilities", "ROLE_IDS": "99"}
)

print(responce.status_code)
assert responce.ok
assert responce.headers["Content-Type"].split(";")[0] == "text/xml"
assert "private_layer" in responce.text


responce = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
    },
)

print(responce.status_code)
print(responce.text)
assert responce.status_code == 403

responce = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
        "ROLE_IDS": "99",
    },
)

print(responce.status_code)
assert responce.ok
assert responce.headers["Content-Type"] == "image/png"
