#!/usr/bin/env python3

import requests

response = requests.get(
    "http://qgisserver", params={"SERVICE": "WMS", "REQUEST": "GetCapabilities"}, timeout=10
)

assert response.ok, f"{response.status_code}\n{response.text}"
assert response.headers["Content-Type"].split(";")[0] == "text/xml", response.headers["Content-Type"]
assert "private_layer" not in response.text, response.text


response = requests.get(
    "http://qgisserver", params={"SERVICE": "WMS", "REQUEST": "GetCapabilities", "ROLE_IDS": "99"}, timeout=10
)

assert response.ok, f"{response.status_code}\n{response.text}"
assert response.headers["Content-Type"].split(";")[0] == "text/xml", response.headers["Content-Type"]
assert "private_layer" in response.text, response.text


response = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
    },
    timeout=10,
)

assert response.status_code == 403, f"{response.status_code}\n{response.text}"

response = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
        "ROLE_IDS": "99",
    },
    timeout=10,
)

assert response.ok, f"{response.status_code}\n{response.text}"
assert response.headers["Content-Type"] == "image/png", response.headers["Content-Type"]
