#!/usr/bin/env python3

import requests

response = requests.get("http://qgisserver", params={"SERVICE": "WMS", "REQUEST": "GetCapabilities"})

print(response.status_code)
assert response.ok
print(response.headers["Content-Type"])
assert response.headers["Content-Type"].split(";")[0] == "text/xml"
assert "private_layer" not in response.text


response = requests.get(
    "http://qgisserver", params={"SERVICE": "WMS", "REQUEST": "GetCapabilities", "ROLE_IDS": "99"}
)

print(response.status_code)
assert response.ok
assert response.headers["Content-Type"].split(";")[0] == "text/xml"
assert "private_layer" in response.text


response = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
    },
)

print(response.status_code)
print(response.text)
assert response.status_code == 403

response = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
        "ROLE_IDS": "99",
    },
)

print(response.status_code)
assert response.ok
assert response.headers["Content-Type"] == "image/png"
