#!/usr/bin/env python3

# Copyright (c) 2025-2026, Camptocamp SA
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import requests

response = requests.get(
    "http://qgisserver",
    params={"SERVICE": "WMS", "REQUEST": "GetCapabilities"},
    timeout=10,
)

assert response.ok, f"{response.status_code}\n{response.text}"
assert response.headers["Content-Type"].split(";")[0] == "text/xml", response.headers["Content-Type"]
assert "private_layer" not in response.text, response.text


response = requests.get(
    "http://qgisserver",
    params={"SERVICE": "WMS", "REQUEST": "GetCapabilities", "ROLE_IDS": "99"},
    timeout=10,
)

assert response.ok, f"{response.status_code}\n{response.text}"
assert response.headers["Content-Type"].split(";")[0] == "text/xml", response.headers["Content-Type"]
assert "private_layer" in response.text, response.text


response = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
    },
    timeout=10,
)

assert response.status_code == 403, f"{response.status_code}\n{response.text}"

response = requests.get(
    "http://qgisserver",
    params={
        "SERVICE": "WMS",
        "REQUEST": "GetMap",
        "VERSION": "1.3.0",
        "FORMAT": "image/png",
        "TRANSPARENT": "true",
        "LAYERS": "private_layer",
        "CRS": "EPSG:21781",
        "WIDTH": "1000",
        "HEIGHT": "1000",
        "BBOX": "400000,80000,600000,90000",
        "ROLE_IDS": "99",
    },
    timeout=10,
)

assert response.ok, f"{response.status_code}\n{response.text}"
assert response.headers["Content-Type"] == "image/png", response.headers["Content-Type"]
