#!/usr/bin/env python3


import transaction
from c2c.template.config import config
from geoalchemy2.shape import from_shape
from shapely.geometry import box

from c2cgeoportal_commons.testing import generate_mappers, get_engine, get_session_factory, get_tm_session

config.init("/tests/project/geomapfish.yaml")

try:
    from c2cgeoportal_commons.models.main import (
        OGCSERVER_AUTH_STANDARD,
        OGCSERVER_TYPE_QGISSERVER,
        LayerWMS,
        OGCServer,
        RestrictionArea,
        Role,
    )
finally:
    pass

area = box(400000, 70000, 800000, 100000)

generate_mappers()
engine = get_engine(config.get_config())
session_factory = get_session_factory(engine)
dbsession = get_tm_session(session_factory, transaction.manager)

ogc_server = OGCServer(
    name="qgisserver",
    type_=OGCSERVER_TYPE_QGISSERVER,
    image_type="image/png",
    auth=OGCSERVER_AUTH_STANDARD,
)
dbsession.add(ogc_server)

role = Role("role")
role.id = 99
dbsession.add(role)

layer = LayerWMS(name="private_layer", layer="private_layer", public=False)
layer.ogc_server = ogc_server

restriction_area = RestrictionArea(
    "restriction_area",
    layers=[layer],
    roles=[role],
    readwrite=True,
    area=from_shape(area, srid=21781),
)
dbsession.add(restriction_area)

dbsession.execute(
    """
INSERT INTO geodata.testpoint
(name, city, country, geom)
VALUES ('test', 'test', 'test', ST_GeomFromText('POINT(500000 80000)', 21781))
"""
)

transaction.commit()
