#!/usr/bin/env python3

# Copyright (c) 2025-2026, Camptocamp SA
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# pylint: disable=invalid-name


import sqlalchemy
import transaction
from c2c.template.config import config
from c2cgeoportal_commons.testing import (
    generate_mappers,
    get_engine,
    get_session_factory,
    get_tm_session,
)
from geoalchemy2.shape import from_shape
from shapely.geometry import box

config.init("/tests/project/geomapfish.yaml")

try:
    from c2cgeoportal_commons.models.main import (
        OGCSERVER_AUTH_STANDARD,
        OGCSERVER_TYPE_QGISSERVER,
        LayerWMS,
        OGCServer,
        RestrictionArea,
        Role,
    )
finally:
    pass

area = box(400000, 70000, 800000, 100000)

generate_mappers()
engine = get_engine(config.get_config())
session_factory = get_session_factory(engine)
dbsession = get_tm_session(session_factory, transaction.manager)

ogc_server = OGCServer(
    name="qgisserver",
    type_=OGCSERVER_TYPE_QGISSERVER,
    image_type="image/png",
    auth=OGCSERVER_AUTH_STANDARD,
)
dbsession.add(ogc_server)

role = Role("role")
role.id = 99
dbsession.add(role)

layer = LayerWMS(name="private_layer", layer="private_layer", public=False)
layer.ogc_server = ogc_server

restriction_area = RestrictionArea(
    "restriction_area",
    layers=[layer],
    roles=[role],
    readwrite=True,
    area=from_shape(area, srid=21781),
)
dbsession.add(restriction_area)

dbsession.execute(
    sqlalchemy.text(
        """
INSERT INTO geodata.testpoint
(name, city, country, geom)
VALUES ('test', 'test', 'test', ST_GeomFromText('POINT(500000 80000)', 21781))
""",
    ),
)

transaction.commit()
