#!/bin/bash -e

function help {
    echo Usage:
    echo ./upgrade VERSION [STEP]
    echo ./upgrade --finalise PACKAGE [DOCKER_TAG]
    exit 1
}

if [ $# -lt 1 ]
then
    help
fi

if [ $1 == '--finalise' ]
then
    shift
    ./build "$@"

    docker-compose down --remove-orphans || true
    DOCKER_TAG=unexisting docker-compose pull --ignore-pull-failures
    docker-compose up -d
    docker-compose exec geoportal alembic --name=main --config=alembic.ini upgrade head

    exit 0
fi

if [ $# -gt 1 ]
then
    args="--step $2"
else
    if [ "$CI" != "true" ]
    then
        docker pull camptocamp/geomapfish:$1
        docker pull camptocamp/geomapfish-tools:$1
        docker pull camptocamp/geomapfish-config-build:$1
    fi
fi

docker run --rm --volume=${PWD}:/src camptocamp/geomapfish-tools:$1 \
        run-git "$(git config --get user.name)" $(git config --get user.email) $(id -u) $(id -g) \
        /src c2cupgrade $args
