#!/bin/bash -eu

echo docker login ***
docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

set -x

if [ $1 == "--geoportal" ]; then
    # Publish the GeoMapFish run
    docker tag camptocamp/geomapfish camptocamp/geomapfish:${MAJOR_VERSION}
    docker push camptocamp/geomapfish:${MAJOR_VERSION}

    # Publish the default geoportal images
    ci/create-new-project ${HOME}/workspace geomapfish
    (
        cd ${HOME}/workspace/geomapfish/
        ./build
    )

    docker tag camptocamp/geomapfish-geoportal camptocamp/geomapfish-geoportal:${MAJOR_VERSION}
    docker push camptocamp/geomapfish-geoportal:${MAJOR_VERSION}
else
    # Publish the GeoMapFish QGIS server images
    docker push camptocamp/geomapfish-qgisserver:gmf${MAJOR_VERSION}-qgis${2}
fi
