#!/bin/bash -ex

GIT_REV=$(git log | head --lines=1 | awk '{{print $2}}')
git checkout gh-pages

if [ -e ${MAIN_BRANCH} ]
then
    git rm -r --force -- ${MAIN_BRANCH}
fi

ci/extract-documentation ${MAIN_BRANCH}

git add --all ${MAIN_BRANCH}
git commit --message="Update documentation for the revision ${GIT_REV}" || true
git push origin gh-pages

# Back to the original branch
git checkout ${GIT_REV}
