#!/bin/bash -e

echo  Prepare .pypirc config
echo "[distutils]" > ~/.pypirc
echo "index-servers = pypi" >> ~/.pypirc
echo "[pypi]" >> ~/.pypirc
echo "username:${PYPI_USERNAME}" >> ~/.pypirc
echo "password:${PYPI_PASSWORD}" >> ~/.pypirc

set -x

# Publish the Python eggs
cd ${PKG}
if [ "${VERSION}" == "${MAJOR_VERSION}" ]
then
    ../.venv/bin/python3 setup.py egg_info --tag-date sdist bdist_wheel
else
    ../.venv/bin/python3 setup.py egg_info --no-date sdist bdist_wheel
fi
../.venv/bin/python3 ../.venv/bin/twine upload dist/*

rm ~/.pypirc
