#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import datetime
import subprocess
import sys

run_cmd = sys.argv[1:]

try:
    subprocess.check_call(run_cmd)
except subprocess.CalledProcessError:
    sys.exit(2)
finally:
    for container in subprocess.check_output(["docker-compose", "ps", "-q"]).decode().strip().split("\n"):
        subprocess.call(["docker", "logs", "--timestamps", container])
