#!/bin/bash -eux

rm -rf ${HOME}/workspace/testgeomapfishapp

ci/create-new-project ${HOME}/workspace
cp ci/docker-compose.override.yaml ${HOME}/workspace/testgeomapfishapp/
cp ci/empty.qgz ${HOME}/workspace/testgeomapfishapp/qgisserver/project.qgz
cp -r ci/test-app-db ${HOME}/workspace/testgeomapfishapp/ci/
cp -r ci/test-external-db ${HOME}/workspace/testgeomapfishapp/ci/
PROJECT_DIR=$(pwd)

cd ${HOME}/workspace/testgeomapfishapp/
c2cciutils-checks
cp ${PROJECT_DIR}/ci/project-config.yaml ci/config.yaml
c2cciutils-checks
./build
docker-compose down
docker-compose up -d
docker-compose exec -T geoportal bash -c 'PGHOST=externaldb PGDATABASE=test wait-db;'
docker-compose exec -T geoportal wait-db
docker-compose ps
docker-compose exec -T geoportal alembic --config=alembic.ini --name=main upgrade head
docker-compose exec -T geoportal alembic --config=alembic.ini --name=static upgrade head
docker-compose exec -T geoportal create-demo-theme
make update-po
docker-compose exec -T geoportal theme2fts

# Commit the l10n files modifications
# To prevent fail on modification files check
#git diff
#git add geoportal/testgeomapfishapp_geoportal/locale/*/LC_MESSAGES/testgeomapfishapp_geoportal-*.po
#git commit -m "Upgrade the po files"

ci/run-dc-logs docker-compose exec -T geoportal ci/waitwsgi https://front/themes
for path in c2c/health_check c2c/health_check?max_level=9 c2c/health_check?checks=check_collector "layers/test/values/type enum" admin/layertree admin/layertree/children; do
    ci/run-dc-logs docker-compose exec -T geoportal ci/test-new-project https://front/${path}
    #docker-compose exec -T geoportal curl --insecure https://front/c2c/debug/stacks?secret=c2c
done
ci/run-dc-logs docker-compose exec -T geoportal ci/test-new-project 'http://qgisserver:8080/mapserv_proxy?SERVICE=WMS&REQUEST=GetCapabilities'
ci/run-dc-logs docker-compose exec -T geoportal curl --insecure https://front/admin/ | grep Login
docker-compose stop qgisserver
ci/run-dc-logs docker-compose exec -T geoportal alembic --config=alembic.ini --name=static downgrade base
ci/run-dc-logs docker-compose exec -T geoportal alembic --config=alembic.ini --name=main downgrade base

cp .env env.int
echo PGHOST_SLAVE=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+') >> env.int
ci/run-dc-logs scripts/db-backup --env=env.int dump.backup
ci/run-dc-logs scripts/db-backup --env=env.int --arg=--schema=main dump.backup
ci/run-dc-logs docker-compose exec -T tools psql --command="ALTER SCHEMA main RENAME TO main_old"
ci/run-dc-logs scripts/db-restore --arg=--clean --arg=--schema=main dump.backup

ci/run-dc-logs docker-compose exec -T tools rm /etc/mapserver/demo.map
ci/run-dc-logs docker-compose exec -T tools mappyfile validate --version=7.6 /etc/mapserver/*.map
docker-compose down
rm -rf ${HOME}/workspace/testgeomapfishapp

docker rmi camptocamp/testgeomapfishapp-geoportal-dev:latest
docker rmi camptocamp/testgeomapfishapp-geoportal:latest
docker rmi camptocamp/testgeomapfishapp-config:latest
