#!/bin/bash -ex

# Prepare .pypirc config
echo "[distutils]" > ~/.pypirc
echo "index-servers = pypi" >> ~/.pypirc
echo "[pypi]" >> ~/.pypirc
echo "repository:https://upload.pypi.org/legacy/" >> ~/.pypirc
echo "username:${TRAVIS_USERNAME}" >> ~/.pypirc
echo "password:${TRAVIS_PASSWORD}" >> ~/.pypirc

# Deploy all the packages on pypi
python commons/setup.py egg_info sdist bdist_wheel upload -r pypi
python geoportal/setup.py egg_info sdist bdist_wheel upload -r pypi
python admin/setup.py egg_info sdist bdist_wheel upload -r pypi
