#!/bin/bash -ex

# Prepare .pypirc config
echo "[distutils]" > ~/.pypirc
echo "index-servers = pypi" >> ~/.pypirc
echo "[pypi]" >> ~/.pypirc
echo "repository:https://upload.pypi.org/legacy/" >> ~/.pypirc
echo "username:${TRAVIS_USERNAME}" >> ~/.pypirc
echo "password:${TRAVIS_PASSWORD}" >> ~/.pypirc

export VERSION=${TRAVIS_TAG}

# Deploy all the packages on pypi
(cd commons; python setup.py egg_info sdist bdist_wheel upload -r pypi)
(cd geoportal; python setup.py egg_info sdist bdist_wheel upload -r pypi)
(cd admin; python setup.py egg_info sdist bdist_wheel upload -r pypi)
