#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright (c) 2013-2016, Camptocamp SA
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.

import os
import argparse
import subprocess
import pyignore


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('commit_range')
    parser.add_argument('base_dir')
    parser.add_argument('ignore_file', nargs='?')
    args = parser.parse_args()

    commit_range = [c for c in args.commit_range.split(".") if c != ""]

    diff = subprocess.check_output(["git", "diff", "--summary", "..".join(commit_range), "--"]).strip()
    files = [] if diff == "" else [
        l.strip().split(" ")[3]
        for l in diff.split('\n')
        if l.startswith(args.base_dir)
    ]
    if args.ignore_file is not None:
        ignore = pyignore.Ignore(os.path.join(args.base_dir, args.ignore_file))
        if len(ignore.filter(files)) == 0:
            exit(1)
    elif len(files) == 0:
        exit(1)

if __name__ == "__main__":
        main()
