#!/usr/bin/env python3

import argparse
import yaml


parser = argparse.ArgumentParser(description='Get and upgrade the minor version.')
parser.add_argument('--reset', action='store_true')
parser.add_argument('--no-save', dest='save', action='store_false')
args = parser.parse_args()

with open("travis/ci.yaml") as ci_file:
    ci = yaml.safe_load(ci_file.read())

minor = 0 if args.reset else ci['minor'] + 1
print(minor)

if args.save:
    ci['minor'] = minor
    with open("travis/ci.yaml", "w") as ci_file:
        ci_file.write(yaml.dump(ci, default_flow_style=False, explicit_start=True))
