#!/bin/bash -ex

# Prepare .pypirc config
echo "[distutils]" > ~/.pypirc
echo "index-servers = pypi" >> ~/.pypirc
echo "[pypi]" >> ~/.pypirc
echo "username:${PYPI_USERNAME}" >> ~/.pypirc
echo "password:${PYPI_PASSWORD}" >> ~/.pypirc

# Publish the Python eggs
cd ${PKG}
python3 setup.py egg_info --no-date sdist bdist_wheel upload -r pypi

rm ~/.pypirc
