#!/bin/bash -ex

docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

TAG=`git tag --list --points-at=HEAD`
LAST_TAG=`git describe --abbrev=0 --tags`
COMMIT=FALSE
VERSION_QGIS=FALSE

if [[ ${TAG} =~ ^[0-9]\.[0-9]\.[0-9]$ ]]
then
    VERSION_QGIS=${TAG}
    .venv/bin/python travis/get-minor --reset
    .venv/bin/python travis/changelog ${TAG}
    COMMIT=TRUE
else
    if [[ ${BRANCH_NAME} =~ ^[0-9]\.[0-9]$ ]]
    then
        VERSION_QGIS=${BRANCH_NAME}
        TAG=${LAST_TAG}.`.venv/bin/python travis/get-minor`
        .venv/bin/python travis/changelog ${TAG}
        COMMIT=TRUE
    fi
fi

if [ ${COMMIT} == TRUE ]
then
    git add travis/ci.yaml travis/changelog.yaml CHANGELOG.md
    git commit -m "Update the minor version and changelog"
    git push origin ${BRANCH_NAME}
fi

DEPLOY_PIP=FALSE
# Get the version to be published
if [ "${TAG}" != "" ]
then
    VERSION=${TAG}
    DEPLOY_PIP=TRUE
elif [ "${BRANCH_NAME}" != "master" ]
then
    VERSION=${BRANCH_NAME//\//_}
else
    VERSION=${MAJOR_VERSION}
fi
export VERSION
if [ ${VERSION_QGIS} == FALSE ]
then
    VERSION_QGIS=${VERSION}
fi

# Publish the GeoMapFish images
for IMAGE in geomapfish-build-dev geomapfish-build geomapfish-config-build
do
    docker tag camptocamp/${IMAGE}:${MAJOR_VERSION} camptocamp/${IMAGE}:${VERSION}
    docker push camptocamp/${IMAGE}:${VERSION}
done

# Publish the GeoMapFish QGIS server images
for QGIS_VERSION in 3.4
do
    docker tag camptocamp/geomapfish-qgisserver:gmf${MAJOR_VERSION}-qgis${QGIS_VERSION} \
        camptocamp/geomapfish-qgisserver:gmf${VERSION_QGIS}-qgis${QGIS_VERSION}
    docker push camptocamp/geomapfish-qgisserver:gmf${VERSION_QGIS}-qgis${QGIS_VERSION}
done

if [ ${DEPLOY_PIP} == TRUE ]
then
    # Publish the Python eggs
    for PKG in commons geoportal admin
    do
        export PKG
    done
fi

# Cleanup
if [ -e ~/.docker ]
then
    rm --recursive --force ~/.docker
fi
