#!/bin/bash -ex

docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

TAG=`git tag --list --points-at=HEAD`
LAST_TAG=`git describe --abbrev=0 --tags`
COMMIT=FALSE

if [[ ${TAG} =~ ^[0-9]\.[0-9]\.[0-9]$ ]]
then
    .venv/bin/python travis/get-minor --reset
    COMMIT=TRUE
else
    if [[ ${BRANCH_NAME} =~ ^[0-9]\.[0-9]$ ]]
    then
        TAG=${LAST_TAG}.`.venv/bin/python travis/get-minor`
        COMMIT=TRUE
    fi
fi

if [ ${COMMIT} == TRUE ]
then
    git add travis/ci.yaml
    git commit -m "Update the minor version"
    git push origin ${BRANCH_NAME}
fi

DEPLOY_PIP=TRUE
# Get the version to be published
if [ "${TAG}" != "" ]
then
    VERSION=${TAG}
elif [ "${BRANCH_NAME}" != "master" ]
then
    VERSION=${BRANCH_NAME/\//_}
    DEPLOY_PIP=FALSE
else
    VERSION=${MAJOR_VERSION}
fi
export VERSION

# Publish the GeoMapFish images
for IMAGE in geomapfish-build-dev geomapfish-build
do
    docker tag camptocamp/${IMAGE}:${MAJOR_VERSION} camptocamp/${IMAGE}:${VERSION}
    docker push camptocamp/${IMAGE}:${VERSION}
done

# Publish the GeoMapFish QGIS server images
for QGIS_VERSION in 3.2 master
do
    docker tag camptocamp/geomapfish-qgisserver:gmf${MAJOR_VERSION}-qgis${QGIS_VERSION} \
        camptocamp/geomapfish-qgisserver:gmf${VERSION}-qgis${QGIS_VERSION}
    docker push camptocamp/geomapfish-qgisserver:gmf${VERSION}-qgis${QGIS_VERSION}
done

if [ ${DEPLOY_PIP} == TRUE ]
then
    # Publish the Python eggs
    for PKG in commons geoportal admin
    do
        ./docker-run --env=PYPI_USERNAME --env=PYPI_PASSWORD --env=VERSION --env=PKG travis/publish-pip
    done
fi

# Cleanup
if [ -e ~/.docker ]
then
    rm --recursive --force ~/.docker
fi
