#!/bin/bash -ex

docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

for IMAGE in geomapfish-build-dev geomapfish-build
do
    if [ "${TRAVIS_TAG}" != "" ]
    then
        docker tag camptocamp/${IMAGE}:${MAJOR_VERSION} camptocamp/${IMAGE}:${TRAVIS_TAG}
        docker push camptocamp/${IMAGE}:${TRAVIS_TAG}
    elif [ "${TRAVIS_BRANCH}" != "master" ]
    then
        BRANCH=${TRAVIS_BRANCH/\//_}
        BRANCH=${BRANCH/\//_}
        docker tag camptocamp/${IMAGE}:${MAJOR_VERSION} camptocamp/${IMAGE}:${BRANCH}
        docker push camptocamp/${IMAGE}:${BRANCH}
    else
        docker push camptocamp/${IMAGE}:${MAJOR_VERSION}
    fi
done

for QGIS_VERSION in 3.2 master
do
    if [ "${TRAVIS_TAG}" != "" ]
    then
        docker tag camptocamp/geomapfish-qgisserver:gmf${MAJOR_VERSION}-qgis${QGIS_VERSION} \
            camptocamp/geomapfish-qgisserver:gmf${TRAVIS_TAG}-qgis${QGIS_VERSION}
        docker push camptocamp/geomapfish-qgisserver:gmf${TRAVIS_TAG}-qgis${QGIS_VERSION}
    elif [ "${TRAVIS_BRANCH}" != "master" ]
    then
        BRANCH=${TRAVIS_BRANCH/\//_}
        BRANCH=${BRANCH/\//_}
        docker tag camptocamp/geomapfish-qgisserver:gmf${MAJOR_VERSION}-qgis${QGIS_VERSION} \
            camptocamp/geomapfish-qgisserver:gmf${BRANCH}-qgis${QGIS_VERSION}
        docker push camptocamp/geomapfish-qgisserver:gmf${BRANCH}-qgis${QGIS_VERSION}
    else
        docker push camptocamp/geomapfish-qgisserver:gmf${MAJOR_VERSION}-qgis${QGIS_VERSION}
    fi
done
