#!/bin/bash -ex

RELEASE_TAG=$MAJOR_VERSION
if [[ $GITHUB_REF =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo Release detected
    RELEASE_TAG=${GITHUB_REF#refs/tags/}
elif [[ $GITHUB_REF =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+\.dev[0-9]+$ ]]; then
    echo Dev release detected
    RELEASE_TAG=${GITHUB_REF#refs/tags/}
elif [[ $GITHUB_REF =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+\.?rc[0-9]+$ ]]; then
    echo RC release detected
    RELEASE_TAG=${GITHUB_REF#refs/tags/}
elif [[ $GITHUB_REF =~ ^refs/heads/[0-9]\.[0-9]$ ]]; then
    echo Release branch detected
    MINOR=$(python3 travis/get-minor --no-save)
    LAST_TAG=$(git describe --abbrev=0 --tags)
    RELEASE_TAG=${LAST_TAG}.${MINOR}
fi

sleep 0.1

echo "##[set-output name=tag;]${RELEASE_TAG}"
