#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (c) 2011-2017, Camptocamp SA
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.

import sys
import json
import subprocess

initial_error_length = 0
initial_access_length = 0

curl_args = ["--connect-timeout", "1", "--max-time", "120", "--retry", "2"]

url = sys.argv[1]

try:
    status_code = subprocess.check_output(
        ["curl", "--write-out", "%{http_code}"] + curl_args + ["--silent", "--output", "/dev/null", url]
    ).decode("utf-8")
except subprocess.CalledProcessError as e:
    print("Exception on curl call: {}".format(e))

    print("RESULT:")
    sys.stdout.flush()
    subprocess.call(["curl"] + curl_args + ["--verbose", url])
    exit(2)

if status_code == "200":
    if len(sys.argv) == 3 and sys.argv[2] == "enum":
        result = subprocess.check_output(
            ["curl"] + curl_args + [url]
        ).decode("utf-8")
        if json.loads(result) == {
            "items": [{
                "label": "car",
                "value": "car"
            }, {
                "label": "train",
                "value": "train"
            }]
        }:
            print("enum OK")
            exit()
        else:
            print("Incorrect result:")
            print(result)
            exit(2)
    print("OK")
    exit()
else:
    print("Bad status code {}".format(status_code))

    print("RESULT:")
    sys.stdout.flush()
    subprocess.call(["curl"] + curl_args + ["--verbose", url])
    exit(2)
