#!/usr/bin/python

import sys
import time
import sqlalchemy

sleep_time = 1

# wait for the DB to be UP
while True:
    print("Waiting for the DB to be reachable")
    try:
        sqlalchemy.create_engine(sys.argv[1]).connect()
        exit(0)
    except Exception as e:
        print(str(e))
        print("Waiting for the DB to be reachable")
        time.sleep(sleep_time)
        sleep_time *= 2
