---
version: '2.0'

services:
  config:
    image: ${DOCKER_BASE}-config:${DOCKER_TAG}
    user: www-data
    environment:
      - VISIBLE_WEB_HOST
      - VISIBLE_WEB_PROTOCOL
      - VISIBLE_ENTRY_POINT
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGPORT_SLAVE
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGSSLMODE
      - PGSCHEMA_STATIC
      - SQLALCHEMY_POOL_RECYCLE
      - SQLALCHEMY_POOL_SIZE
      - SQLALCHEMY_MAX_OVERFLOW
      - GEOPORTAL_INTERNAL_URL
      - GEOPORTAL_INTERNAL_HOST
      - GEOPORTAL_INTERNAL_PORT
      - TILECLOUDCHAIN_INTERNAL_URL
      - TILECLOUDCHAIN_INTERNAL_HOST
      - TILECLOUDCHAIN_INTERNAL_PORT
      - MUTUALIZED_PRINT_URL
      - DISABLE_MUTUALIZED_PRINT
      - DISABLE_LOCAL_PRINT
      - MAPSERVER_URL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_SERVICENAME
      - REDIS_TIMEOUT
      - TILEGENERATION_SQS_QUEUE
      - TILEGENERATION_S3_BUCKET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_ENDPOINT

  print:
    image: camptocamp/mapfish_print:3.27
    user: www-data
    restart: unless-stopped
    environment:
      - CATALINA_OPTS
      - PGOPTIONS

  mapserver:
    image: camptocamp/mapserver:7.6
    user: www-data
    restart: unless-stopped
    entrypoint: []
    environment:
      - PGOPTIONS

  qgisserver:
    image: camptocamp/geomapfish-qgisserver:gmf${GEOMAPFISH_MAIN_VERSION}-qgis${QGIS_VERSION}
    user: www-data
    restart: unless-stopped
    environment:
      - C2C_REDIS_URL
      - C2C_REDIS_SENTINELS
      - C2C_REDIS_TIMEOUT
      - C2C_REDIS_SERVICENAME
      - C2C_REDIS_DB
      - C2C_BROADCAST_PREFIX
      - PGOPTIONS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_ENDPOINT
      - CPL_VSIL_CURL_USE_CACHE
      - CPL_VSIL_CURL_CACHE_SIZE
      - CPL_VSIL_CURL_USE_HEAD
      - GDAL_DISABLE_READDIR_ON_OPEN
      - QGIS_SERVER_LOG_LEVEL=2
      - LOG_LEVEL=INFO
      - LOG_TYPE
      - C2CGEOPORTAL_LOG_LEVEL
      - SQL_LOG_LEVEL
      - OTHER_LOG_LEVEL

  tinyows:
    image: camptocamp/tinyows:master
    user: www-data
    restart: unless-stopped

  redis:
    image: redis:6
    user: www-data
    restart: unless-stopped
    command:
      - redis-server
      - --save
      - ''
      - --appendonly
      - 'no'
      - --maxmemory
      - 512mb
      - --maxmemory-policy
      - volatile-lru
      - --tcp-keepalive
      - '30'

  redis_master:
    image: redis:6

  redis_slave:
    image: redis:6
    command: redis-server --slaveof redis_master 6379

  redis_sentinel:
    image: camptocamp/c2cwsgiutils-redis-sentinel:6
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=1
      - MASTER=redis_master

  tilecloudchain:
    image: camptocamp/tilecloud-chain:1.15
    user: www-data
    restart: unless-stopped
    environment:
      - DEVELOPMENT
      - GUNICORN_PARAMS
      - VISIBLE_ENTRY_POINT
      - TILEGENERATION_CONFIGFILE=/etc/tilegeneration/config.yaml
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - C2C_BASE_PATH
      - C2C_REDIS_URL
      - C2C_REDIS_SENTINELS
      - C2C_REDIS_TIMEOUT
      - C2C_REDIS_SERVICENAME
      - C2C_REDIS_DB
      - C2C_BASE_PATH=/tiles/c2c
      - C2C_BROADCAST_PREFIX=broadcast_tilecloudchain_
      - C2C_REQUESTS_DEFAULT_TIMEOUT
      - C2C_LOG_VIEW_ENABLED=TRUE
      - C2C_DEBUG_VIEW_ENABLED=TRUE
      - C2C_SQL_PROFILER_ENABLED=TRUE
      - C2C_PROFILER_PATH
      - C2C_PROFILER_MODULES
      - C2C_SECRET
      - TILECLOUD_LOG_LEVEL
      - TILECLOUD_CHAIN_LOG_LEVEL
      - C2CWSGI_LOG_LEVEL
      - OTHER_LOG_LEVEL
      - LOG_TYPE

  tilegeneration_slave:
    image: camptocamp/tilecloud-chain:1.15
    user: www-data
    restart: unless-stopped
    entrypoint:
      - generate_tiles
      - --role=slave
      - --daemon
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  geoportal:
    image: ${DOCKER_BASE}-geoportal:${DOCKER_TAG}
    user: www-data
    restart: unless-stopped
    environment:
      - DEVELOPMENT
      - VISIBLE_ENTRY_POINT
      - PACKAGE
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGPORT_SLAVE
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGSSLMODE
      - PGSCHEMA_STATIC
      - PGOPTIONS
      - SQLALCHEMY_POOL_RECYCLE
      - SQLALCHEMY_POOL_SIZE
      - SQLALCHEMY_MAX_OVERFLOW
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_ENDPOINT
      - GUNICORN_PARAMS
      - VISIBLE_WEB_HOST
      - VISIBLE_WEB_PROTOCOL
      - AUTHTKT_TIMEOUT
      - AUTHTKT_REISSUE_TIME
      - AUTHTKT_MAXAGE
      - AUTHTKT_SECRET
      - AUTHTKT_COOKIENAME
      - AUTHTKT_HTTP_ONLY
      - AUTHTKT_SECURE
      - AUTHTKT_SAMESITE
      - BASICAUTH
      - TINYOWS_URL
      - MAPSERVER_URL
      - QGISSERVER_URL
      - PRINT_URL
      - DEVSERVER_HOST
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_SERVICENAME
      - REDIS_TIMEOUT
      - C2C_BASE_PATH
      - C2C_REDIS_URL
      - C2C_REDIS_SENTINELS
      - C2C_REDIS_TIMEOUT
      - C2C_REDIS_SERVICENAME
      - C2C_REDIS_DB
      - C2C_BROADCAST_PREFIX
      - C2C_REQUESTS_DEFAULT_TIMEOUT
      - C2C_LOG_VIEW_ENABLED=TRUE
      - C2C_SQL_PROFILER_ENABLED=TRUE
      - C2C_PROFILER_PATH
      - C2C_PROFILER_MODULES
      - C2C_DEBUG_VIEW_ENABLED=TRUE
      - C2C_SECRET
      - LOG_LEVEL
      - C2CGEOPORTAL_LOG_LEVEL
      - SQL_LOG_LEVEL
      - GUNICORN_LOG_LEVEL
      - OTHER_LOG_LEVEL
      - DOGPILECACHE_LOG_LEVEL
      - LOG_TYPE

  tools:
    image: camptocamp/geomapfish-tools:${GEOMAPFISH_VERSION}
    restart: unless-stopped
    environment:
      - PGSCHEMA
      # From geoportal
      - DEVELOPMENT
      - VISIBLE_ENTRY_POINT
      - PACKAGE
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGPORT_SLAVE
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGSSLMODE
      - PGSCHEMA_STATIC
      - PGOPTIONS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_ENDPOINT
      - GUNICORN_PARAMS
      - VISIBLE_WEB_HOST
      - VISIBLE_WEB_PROTOCOL
      - AUTHTKT_TIMEOUT
      - AUTHTKT_REISSUE_TIME
      - AUTHTKT_MAXAGE
      - AUTHTKT_SECRET
      - AUTHTKT_COOKIENAME
      - AUTHTKT_HTTP_ONLY
      - AUTHTKT_SECURE
      - AUTHTKT_SAMESITE
      - BASICAUTH
      - TINYOWS_URL
      - MAPSERVER_URL
      - QGISSERVER_URL
      - PRINT_URL
      - DEVSERVER_HOST
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - REDIS_SERVICENAME
      - REDIS_TIMEOUT
      - C2C_BASE_PATH
      - C2C_REDIS_URL
      - C2C_REDIS_SENTINELS
      - C2C_REDIS_TIMEOUT
      - C2C_REDIS_SERVICENAME
      - C2C_REDIS_DB
      - C2C_BROADCAST_PREFIX
      - C2C_REQUESTS_DEFAULT_TIMEOUT
      - C2C_LOG_VIEW_ENABLED=TRUE
      - C2C_SQL_PROFILER_ENABLED=TRUE
      - C2C_PROFILER_PATH
      - C2C_PROFILER_MODULES
      - C2C_DEBUG_VIEW_ENABLED=TRUE
      - C2C_SECRET
      - LOG_LEVEL
      - C2CGEOPORTAL_LOG_LEVEL
      - SQL_LOG_LEVEL
      - GUNICORN_LOG_LEVEL
      - OTHER_LOG_LEVEL
      - DOGPILECACHE_LOG_LEVEL
      - LOG_TYPE

  alembic:
    image: ${DOCKER_BASE}-geoportal:${DOCKER_TAG}
    user: www-data
    entrypoint: []
    command:
      - alembic
      - --name=static
      - upgrade
      - head
    environment:
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGPORT_SLAVE
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGSSLMODE
      - PGSCHEMA_STATIC
      - LOG_TYPE

  front:
    image: haproxy:2.2
    restart: unless-stopped
    volumes:
      - /dev/log:/dev/log:rw
    command:
      - haproxy
      - -f
      - /etc/${FRONT_CONFIG}
    ports:
      - ${DOCKER_PORT}:${FRONT_INNER_PORT}

  webpack_dev_server:
    image: ${DOCKER_BASE}-geoportal-dev:${DOCKER_TAG}
    volumes:
      - ./geoportal/${PACKAGE}_geoportal/static-ngeo:/app/${PACKAGE}_geoportal/static-ngeo
    environment:
      - VISIBLE_ENTRY_POINT
      - VISIBLE_WEB_HOST
      - VISIBLE_WEB_PROTOCOL
      - PGHOST
      - PGHOST_SLAVE
      - PGPORT
      - PGPORT_SLAVE
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGSSLMODE
      - PGSCHEMA_STATIC
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - AWS_S3_ENDPOINT
