---

# A compose file for the build.

version: '2'

volumes:
  build:
    external:
      name: ${BUILD_VOLUME_NAME}

services:
  config:
    extends:
      file: docker-compose-lib.yaml
      service: config

  mapserver:
    extends:
      file: docker-compose-lib.yaml
      service: mapserver
    volumes_from:
      - config:rw

  ## qgisserver:
  ##   extends:
  ##     file: docker-compose-lib.yaml
  ##     service: qgisserver
  ##   volumes_from:
  ##     - config:ro
  ##   environment:
  ##     # Single QGIS project files
  ##     QGIS_PROJECT_FILE: /etc/qgisserver/project.qgz
  ##     GEOMAPFISH_OGCSERVER: <OGC server name>
  ##     # Multiple QGIS project files
  ##     # QGIS_PROJECT_FILE:
  ##     # GEOMAPFISH_ACCESSCONTROL_CONFIG: /etc/qgisserver/accesscontrol_config.yaml

  build:
    extends:
      file: docker-compose-lib.yaml
      service: build
