name: Clean docker hub tags

on: delete

jobs:
  clean:
    runs-on: ubuntu-22.04
    name: Clean docker hub tags
    timeout-minutes: 5
    env:
      SUMMON_PROVIDER: /usr/local/bin/gopass
    steps:
      - uses: actions/checkout@v1
      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
      - name: Clean docker hub tags
        run: summon --environment dockerhub_user_pass ci/clean-dockerhub-tags
