---

name: Lint pull request title

on:
  push:
  pull_request:
    types:
      - edited

jobs:
  lint:
    name: Lint pull request title
    runs-on: ubuntu-18.04
    timeout-minutes: 5

    steps:
      - uses: morrisoncole/pr-lint-action@v1.0.0
        with:
          title-regex: "^[A-Z0-9].*"
          on-failed-regex-comment: "The title should start with a capital."
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
