---

name: Lint Pull request title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint:
    name: Lint Pull request title
    runs-on: ubuntu-18.04

    steps:
      - uses: morrisoncole/pr-lint-action@v1.0.0
        with:
          title-regex: "^[A-Z0-9].*"
          on-failed-regex-comment: "The title should starts with a capital."
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
