---
name: Automatic Rebase

on:
  push:
  pull_request:
    types:
      - labeled

jobs:
  auto-rebase:
    name: Automatic Rebase
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: camptocamp/AutoRebase@master
        with:
          github_token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
