name: Rebuild 2.7

on:
  schedule:
    - cron: '30 3 * * *'

jobs:
  main:
    runs-on: ubuntu-22.04
    name: Rebuild 2.7
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '2.7'

    env:
      MAIN_BRANCH: '2.7'
      MAJOR_VERSION: '2.7'

    steps:
      - run: '! ls BACKPORT_TODO'
      - run: df -h
      - run: docker system prune --all --force

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}
          ref: ${{ env.MAIN_BRANCH }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker transifex

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: scripts/get-version --auto-increment --github
        id: version

      - run: python3 -m pip install --user --requirement=requirements.txt

      # Build images
      - run: make build-runner
      - run: make build-tools
      - run: make checks
        if: always()
      - run: make build-config

      # Build and lint QGIS images
      - run: docker build --target=lint --build-arg=VERSION=3.22 docker/qgisserver
      - run: QGIS_VERSION=3.22 make build-qgisserver

      # Tests
      - run: make preparetest
      - run: docker-compose logs --timestamps
        if: failure()
      # Similar to: make tests-commons
      - run: >
          docker-compose exec -T tests coverage run
          --source=/opt/c2cgeoportal/commons/c2cgeoportal_commons
          --module pytest --verbose --color=yes --junitxml=/tmp/commons.xml
          /opt/c2cgeoportal/commons/tests
      - run: c2cciutils-docker-logs
      # Similar to: make tests-geoportal
      - run: >
          docker-compose exec -T tests coverage run --append
          --source=/opt/c2cgeoportal/geoportal/c2cgeoportal_geoportal
          --module pytest --verbose --color=yes --junitxml=/tmp/geoportal.xml
          /opt/c2cgeoportal/geoportal/tests
      - run: c2cciutils-docker-logs
      # Similar to: make tests-admin
      - run: >
          docker-compose exec -T tests coverage run --append
          --source=/opt/c2cgeoportal/admin/c2cgeoportal_admin
          --module pytest --verbose --color=yes --junitxml=/tmp/admin.xml
          /opt/c2cgeoportal/admin/tests
      - run: c2cciutils-docker-logs
      # Similar to: make tests-qgisserver
      - run: >
          docker-compose exec -T qgisserver-tests coverage run
          --source=/var/www/plugins/geomapfish_qgisserver
          --module pytest --verbose --color=yes --junitxml=/tmp/qgis.xml
          /src/tests/functional
      - run: c2cciutils-docker-logs
      - name: Extract tests artifacts
        run: |
          docker-compose exec -T tests coverage report
          docker-compose exec -T tests coverage html --directory=/tmp/coverage
          docker-compose exec -T qgisserver-tests coverage report
          docker-compose exec -T qgisserver-tests coverage html --directory=/tmp/coverage
          mkdir --parent artifacts/geoportal-coverage
          mkdir --parent artifacts/qgisserver-plugin-coverage
          docker cp c2cgeoportal_tests_1:/tmp/coverage/ artifacts/geoportal-coverage/
          docker cp c2cgeoportal_qgisserver-tests_1:/tmp/coverage/ artifacts/qgisserver-plugin-coverage/
        if: always()
        continue-on-error: true
      - run: c2cciutils-docker-logs
        if: always()
      - run: docker-compose down

      - uses: actions/upload-artifact@v3
        with:
          name: Geoportal coverage
          path: artifacts/geoportal-coverage/
          if-no-files-found: ignore
          retention-days: 5
      - uses: actions/upload-artifact@v3
        with:
          name: QGISserver plugin coverage
          path: artifacts/qgisserver-plugin-coverage/
          if-no-files-found: ignore
          retention-days: 5
      - run: sudo git clean -fdx

      # Documentation
      - run: >
          docker build --tag=camptocamp/geomapfish-doc
          --build-arg=MAJOR_VERSION=${MAJOR_VERSION}
          --build-arg=MAIN_BRANCH=${MAIN_BRANCH}
          doc

      - name: Extract documentation
        run: ci/extract-documentation artifacts/documentations/ || true
        if: always()

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Documentation
          path: artifacts/documentations/
          if-no-files-found: ignore
          retention-days: 5

      # Test App
      - run: ci/test-app
      - name: Docker logs
        run: |
          cd ${HOME}/workspace/testgeomapfishapp/
          c2cciutils-docker-logs
        if: failure()
        continue-on-error: true

      - name: Init Git
        run:
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository
          }}
      - run: make build-tools
      - run: make build-runner
      - run: make build-config

      - run: ci/create-new-project ${HOME}/workspace geomapfishapp
      - run: (cd ${HOME}/workspace/geomapfishapp/; ./build)

      - name: Update the changelog
        run: ci/changelog ${{ steps.version.outputs.full }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git diff CHANGELOG.md

      - name: Publish feature branch
        run: |
          c2cciutils-publish --branch=${{ matrix.branch }} --type=rebuild
          c2cciutils-publish --type=rebuild --version=${{ steps.version.outputs.major_minor }}

      - run: >
          docker run --rm --volume=/var/run/docker.sock:/var/run/docker.sock nate/dockviz
          images --tree
        if: always()
      - run: docker images
        if: always()
      - run: docker system df
        if: always()
      - run: df -h
        if: always()
