---
name: QGIS rebuild

on:
  schedule:
    - cron: '30 3 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    name: QGIS rebuild
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        version:
          # Old LTR
          - '3.4'
          # LTR
          - '3.10'
          - '3.12'
          # Last
          - '3.14'

    env:
      MAIN_BRANCH: 2.5
      MAJOR_VERSION: 2.5
      CI: true
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin
      SUMMON_PROVIDER: /usr/local/bin/gopass

    steps:
      - uses: actions/checkout@v1

      - run: docker pull camptocamp/geomapfish:${{ env.MAJOR_VERSION }}
      - run: docker tag camptocamp/geomapfish:${{ env.MAJOR_VERSION }} camptocamp/geomapfish
      - run: make build-test-db

      - name: Build QGIS server
        run: |
          docker build --target=runner --build-arg=VERSION=${{ matrix.version }} \
          --tag=camptocamp/geomapfish-qgisserver \
          docker/qgisserver;
          docker tag camptocamp/geomapfish-qgisserver \
          camptocamp/geomapfish-qgisserver:gmf${MAJOR_VERSION}-qgis${{ matrix.version }}

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        if: github.repository == 'camptocamp/c2cgeoportal'

      - name: Acceptence tests
        run: |
          cd docker/qgisserver
          docker-compose up -d
          docker-compose exec -T tests /tests/wait-db
          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=main upgrade head
          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=static upgrade head
          docker-compose exec -T tests /tests/fill-db
          ../../ci/run-dc-logs docker-compose exec -T tests /tests/acceptance-tests
          docker-compose down

      - name: Publish
        run: |
          summon --yaml '
            DOCKER_USERNAME: !var gs/ci/dockerhub/username
            DOCKER_PASSWORD: !var gs/ci/dockerhub/password
          ' ci/publish-daily --qgisserver ${{ matrix.version }}
        if: github.repository == 'camptocamp/c2cgeoportal'
