name: QGIS rebuild 2.6

on:
  schedule:
    - cron: '30 3 * * *'

jobs:
  main:
    runs-on: ubuntu-22.04
    name: QGIS rebuild 2.6
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '2.6'
        version:
          # Old LTR
          - '3.10'
          # Last LTR
          - '3.16'

    env:
      MAIN_BRANCH: ${{ matrix.branch }}
      MAJOR_VERSION: ${{ matrix.branch }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/c2cgeoportal'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - run: docker pull camptocamp/geomapfish:${{ env.MAJOR_VERSION }}
      - run: docker tag camptocamp/geomapfish:${{ env.MAJOR_VERSION }} camptocamp/geomapfish
      - run: make build-test-db

      - name: Build QGIS server
        run: |
          docker build --target=runner --build-arg=VERSION=${{ matrix.version }} \
          --tag=camptocamp/geomapfish-qgisserver \
          docker/qgisserver;
          docker tag camptocamp/geomapfish-qgisserver \
          camptocamp/geomapfish-qgisserver:gmflatest-qgis${{ matrix.version }}

      - name: Test library availability
        run:
          "! ( docker run --rm camptocamp/geomapfish-qgisserver ldd /usr/local/bin/qgis_mapserv.fcgi | grep 'not
          found' )"

      - name: Acceptance tests
        run: |
          cd docker/qgisserver
          docker compose up -d
          docker compose exec -T tests /tests/wait-db
          docker compose exec -T tests alembic --config=/tests/alembic.ini --name=main upgrade head
          docker compose exec -T tests alembic --config=/tests/alembic.ini --name=static upgrade head
          docker compose exec -T tests /tests/fill-db
          ../../ci/run-dc-logs docker compose exec -T tests /tests/acceptance-tests
          docker compose down

      - run: scripts/get-version --auto-increment --github
        id: version
        if: github.repository == 'camptocamp/c2cgeoportal'

      - name: Publish feature branch
        run: |
          c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }} --group=qgis-${{ matrix.version }}
