---
name: QGIS rebuild 2.5

on:
  schedule:
    - cron: '30 3 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    name: QGIS rebuild 2.5
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '2.5'
        version:
          # Old LTR
          - '3.4'
          # LTR
          - '3.10'
          - '3.12'
          # Last
          - '3.14'

    env:
      MAIN_BRANCH: ${{ matrix.branch }}
      MAJOR_VERSION: ${{ matrix.branch }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/c2cgeoportal'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - run: docker pull camptocamp/geomapfish:${{ env.MAJOR_VERSION }}
      - run: docker tag camptocamp/geomapfish:${{ env.MAJOR_VERSION }} camptocamp/geomapfish
      - run: make build-test-db

      - name: Build QGIS server
        run: |
          docker build --target=runner --build-arg=VERSION=${{ matrix.version }} \
          --tag=camptocamp/geomapfish-qgisserver \
          docker/qgisserver;
          docker tag camptocamp/geomapfish-qgisserver \
          camptocamp/geomapfish-qgisserver:gmflatest-qgis${{ matrix.version }}

      - name: Acceptance tests
        run: |
          cd docker/qgisserver
          docker-compose up -d
          docker-compose exec -T tests /tests/wait-db
          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=main upgrade head
          docker-compose exec -T tests alembic --config=/tests/alembic.ini --name=static upgrade head
          docker-compose exec -T tests /tests/fill-db
          ../../ci/run-dc-logs docker-compose exec -T tests /tests/acceptance-tests
          docker-compose down

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.version }}
          --group=qgis-${{ matrix.version }}
        if: github.repository == 'camptocamp/c2cgeoportal'
