name: Reset 4th version on tag

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  common:
    runs-on: ubuntu-24.04
    name: Reset 4th version on tag
    timeout-minutes: 30
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v5

      - run: scripts/get-main-version --github
        id: main-version

      - uses: actions/checkout@v5
        with:
          ref: ${{ steps.main-version.outputs.main_branch }}

      - run: scripts/get-version --auto-increment

      - name: Push version
        run: |
          set -eux
          git add ci/ci.yaml
          git diff --staged --quiet || (\
            git commit -m "[skip ci] Update the minor version"; \
            git push origin HEAD:${{ steps.main-version.outputs.main_branch }} \
          )
